### ISSUE TITLE
Rails 6 - undefined method `view_renderer='

### ISSUE THREAD

**Issue by agungyuliaji** [komposable/komponent#133] opened 2019-03-17 13:01 UTC
How to reproduce:
- use rails 6 6.0.0.beta3
- install komponet gem
- just follow button generate example from Readme
- render the button componet into the view, `component 'button'`

**Comment by Spone** [comment] 2019-03-17 15:30
Hi @agungyuliaji 

which version of Komponent are you using?

Thanks in advance.

**Comment by agungyuliaji** [comment] 2019-03-17 19:57
Hi @Spone
it's ver. 2.2.0

**Comment by Spone** [comment] 2019-03-17 21:33
Can you try with 3.0.0.beta1?

**Comment by ogntng** [comment] 2019-03-18 08:55
still same, the core problem is, `view_renderer=` is not exist
i've updated my PR, fix the test run, https://github.com/komposable/komponent/pull/134

but now I think maybe this is a **little far away** (since rails 6 is beta),
maybe we can close this issue,
and I will use the monkeypatch mode for my issue. 

thanks bro 👊

**Comment by agungyuliaji** [comment] 2019-03-18 08:57
still same with `3.0.0.beta1`, the core problem is, `view_renderer=` is not exist
i've updated my PR, fix the test run, https://github.com/komposable/komponent/pull/134

but now I think maybe this is a **little far away** (since rails 6 is beta),
maybe we can close this issue,
and I will use the monkeypatch mode for my issue. 

thanks bro 👊

**Comment by Spone** [comment] 2019-03-18 09:24
Thanks for the feedback. I'll keep the issue open because it's weird our tests haven't detected the issue. I reopened #118 to update our tests to the new beta3.

**Comment by Spone** [comment] 2019-03-26 06:50
Our tests were actually not run on Rails 6 :man_facepalming: 

I managed to reproduce the issue in the tests: https://travis-ci.org/komposable/komponent/jobs/511340428

**Closed** 2019-03-28 09:15 UTC
Labels: bug

**Comment by 0x2C6** [comment] 2019-04-30 20:59
Same problem here :D I should also be good if it moves and renames javascript to frontend and also copy channels and other folders

**Comment by 0x2C6** [comment] 2019-04-30 21:29
Okay, temporary solution.
Clone the repo and move it to the application's lib folder
update Gemfile and add
```ruby
gem 'komponent', path: './lib/komponent'
```
Edit component_renderer file as below or just replace "view_renderer" instance variables to "render"

```ruby
def initialize(controller, view_flow = nil)
      @context = controller.view_context.dup
      @render = @context.view_renderer
      @lookup_context = @render.lookup_context = @render.lookup_context.dup
      @view_flow = view_flow
    end
```

Works for me try both 5.1.x and 6.0rc

**Comment by alec-c4** [comment] 2019-06-23 12:05
Hi! Maybe it would be better to create separate branch with this patch?
